---
title: "Batch Effect Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
data_dir <- '/nfs/data/omnideconv_benchmarking_clean/benchmark_results/results_batcheffecct'
ref_dir <- '/nfs/data/omnideconv_benchmarking_clean/data/singleCellXGeneCensus/'

result_dirs <- list.files(data_dir, full.names = T)


res <- lapply(result_dirs, function(i){
  metrics_file <- paste0(i,'/results_metric.rds')
  if(file.exists(metrics_file)){
      metrics <- readRDS(metrics_file)
  }else{
    return(NULL)
  }
  
  sc_dataset <- unique(metrics$runtimes$sc_ds)
  bulk_dataset <- unique(metrics$runtimes$bulk_ds)

  anno_singlecell <- readRDS(paste0(ref_dir,'/',sc_dataset,'/celltype_annotations.rds'))

  #df <- metrics$cor_cell_type
  df <- metrics$cor_cell_type
  df$sc_dataset <- sc_dataset
  df$bulk_dataset <- bulk_dataset
  df$method <- unique(metrics$runtimes$method)
  
  return(df)
})
```

```{r}
df <- bind_rows(res)

ggplot(df, aes(x=cell_type, y=sc_dataset, fill=cor, label = round(cor, 2)))+
  geom_tile()+
  facet_grid(bulk_dataset~method)+
  geom_text(color='white')+
  theme_minimal()
```

